services:
  - type: web
    name: vault-bank
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false

      - key: SESSION_SECRET
        sync: false

      - key: SMTP_HOST
        value: smtp.resend.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: resend
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: Vault Bank <noreply@vaultbank.com>

      - key: APP_URL
        sync: false
